# Generated by Django 5.0.2 on 2024-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('emailId', models.EmailField(default=None, max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
